[package]
name = "flight-image-geotagger-rs"
description = "Geotag images taken on a commercial flight."
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
serde = "1.0.217"
